#include "lu5_bindings.h"
#include "lu5_window.h"
#include "lu5_geometry.h"

#include "bindings/classes.h"
#include "bindings/lu5_math.h"
#include "bindings/lu5_vector.h"

#include "bindings/mouse.h"
#include "bindings/keyboard.h"
#include "bindings/window.h"
#include "bindings/setting.h"
#include "bindings/io.h"
#include "bindings/models.h"
#include "bindings/shapes.h"
#include "bindings/shapes3D.h"
#include "bindings/transform.h"
#include "bindings/camera.h"
#include "bindings/typography.h"
#include "bindings/image.h"

static void lu5_register_constants(lua_State *L) 
{
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "LEFT_ARROW" , LU5_KEY_LEFT_ARROW);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "RIGHT_ARROW", LU5_KEY_RIGHT_ARROW);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "UP_ARROW"   , LU5_KEY_UP_ARROW);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "DOWN_ARROW" , LU5_KEY_DOWN_ARROW);

	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "ENTER"	  , LU5_KEY_ENTER);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "BACKSPACE"  , LU5_KEY_BACKSPACE);

	// NUMBER KEYS (0-9)
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_0" , LU5_KEY_0);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_1" , LU5_KEY_1);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_2" , LU5_KEY_2);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_3" , LU5_KEY_3);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_4" , LU5_KEY_4);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_5" , LU5_KEY_5);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_6" , LU5_KEY_6);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_7" , LU5_KEY_7);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_8" , LU5_KEY_8);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_9" , LU5_KEY_9);

	// Alphabet Keys
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_A" , LU5_KEY_A);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_B" , LU5_KEY_B);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_C" , LU5_KEY_C);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_D" , LU5_KEY_D);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_E" , LU5_KEY_E);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_F" , LU5_KEY_F);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_G" , LU5_KEY_G);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_H" , LU5_KEY_H);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_I" , LU5_KEY_I);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_J" , LU5_KEY_J);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_K" , LU5_KEY_K);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_L" , LU5_KEY_L);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_M" , LU5_KEY_M);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_N" , LU5_KEY_N);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_O" , LU5_KEY_O);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_P" , LU5_KEY_P);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_Q" , LU5_KEY_Q);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_R" , LU5_KEY_R);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_S" , LU5_KEY_S);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_T" , LU5_KEY_T);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_U" , LU5_KEY_U);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_V" , LU5_KEY_V);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_W" , LU5_KEY_W);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_X" , LU5_KEY_X);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_Y" , LU5_KEY_Y);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_Z" , LU5_KEY_Z);

	// Other common keys
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_BACKSLASH", LU5_KEY_BACKSLASH);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_GRAVE_ACCENT" , LU5_KEY_GRAVE_ACCENT);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_ESCAPE" , LU5_KEY_ESCAPE);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_TAB" , LU5_KEY_TAB);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_INSERT" , LU5_KEY_INSERT);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_DELETE", LU5_KEY_DELETE);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_PAGE_UP" , LU5_KEY_PAGE_UP);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_PAGE_DOWN", LU5_KEY_PAGE_DOWN);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_HOME", LU5_KEY_HOME);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_END", LU5_KEY_END);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "KEY_CAPS_LOCK", LU5_KEY_CAPS_LOCK);

	// GL Primitives
	LUA_ADD_INTEGER_GLOBAL_BY_NAME(L, "POINTS"		, GL_POINTS);
	LUA_ADD_INTEGER_GLOBAL_BY_NAME(L, "QUADS"		, GL_QUADS);
	LUA_ADD_INTEGER_GLOBAL_BY_NAME(L, "LINES"		, GL_LINES);
	LUA_ADD_INTEGER_GLOBAL_BY_NAME(L, "LINE_STRIP"	, GL_LINE_STRIP);
	LUA_ADD_INTEGER_GLOBAL_BY_NAME(L, "LINE_LOOP"	, GL_LINE_LOOP);
	LUA_ADD_INTEGER_GLOBAL_BY_NAME(L, "TRIANGLES"	, GL_TRIANGLES);
	LUA_ADD_INTEGER_GLOBAL_BY_NAME(L, "TRIANGLE_STRIP", GL_TRIANGLE_STRIP);
	LUA_ADD_INTEGER_GLOBAL_BY_NAME(L, "TRIANGLE_FAN" , GL_TRIANGLE_FAN);
	LUA_ADD_INTEGER_GLOBAL_BY_NAME(L, "QUAD_STRIP"	, GL_QUAD_STRIP);

	// rectMode constants
	LUA_ADD_INTEGER_GLOBAL_BY_NAME(L, "CENTER", LU5_RECTMODE_CENTER);
	LUA_ADD_INTEGER_GLOBAL_BY_NAME(L, "CORNER", LU5_RECTMODE_CORNER);
	LUA_ADD_INTEGER_GLOBAL_BY_NAME(L, "RADIUS", LU5_RECTMODE_RADIUS);

	// textAlign constants
	LUA_ADD_INTEGER_GLOBAL_BY_NAME(L, "RIGHT", LU5_TEXTALIGN_RIGHT);
	LUA_ADD_INTEGER_GLOBAL_BY_NAME(L, "LEFT", LU5_TEXTALIGN_LEFT);
	// LU5_TEXTALIGN_CENTER == LU5_RECTMODE_CENTER

	// Math constants
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "TWO_PI"	, LU5_TWO_PI);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "PI"		, LU5_PI);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "HALF_PI"   , LU5_HALF_PI);
	LUA_ADD_NUMBER_GLOBAL_BY_NAME(L, "QUARTER_PI", LU5_QUARTER_PI);
}

void lu5_register_symbols(lua_State *L) 
{
	LUA_ADD_STRING_GLOBAL_BY_NAME(L, "VERSION", LU5_VERSION);

	// IO
	LUA_ADD_FUNCTION(L, print);
	LUA_ADD_FUNCTION(L, loadStrings);
	LUA_ADD_FUNCTION(L, loadText);

	// Window
	LUA_ADD_INTEGER_GLOBAL_BY_NAME(L, "GL2D", LU5_GL2D);
	LUA_ADD_INTEGER_GLOBAL_BY_NAME(L, "GL3D", LU5_GL3D);
	LUA_ADD_FUNCTION(L, createWindow);
	LUA_ADD_FUNCTION(L, saveWindow);
	LUA_ADD_FUNCTION(L, background);
	LUA_ADD_FUNCTION(L, frameRate);
	LUA_ADD_FUNCTION(L, noLoop);
	LUA_ADD_FUNCTION(L, loop);

	// Input
	LUA_ADD_FUNCTION(L, keyIsDown);

	// Setting
	LUA_ADD_FUNCTION(L, push);
	LUA_ADD_FUNCTION(L, pop);
	LUA_ADD_FUNCTION(L, rectMode);
	LUA_ADD_FUNCTION(L, fill);
	LUA_ADD_FUNCTION(L, noFill);	
	LUA_ADD_FUNCTION(L, stroke);
	LUA_ADD_FUNCTION(L, noStroke);
	LUA_ADD_FUNCTION(L, strokeWeight);	

	LUA_ADD_FUNCTION(L, beginShape);
	LUA_ADD_FUNCTION(L, vertex);
	LUA_ADD_FUNCTION(L, endShape);

	// Shapes
	LUA_ADD_FUNCTION(L, circle);
	LUA_ADD_FUNCTION(L, ellipse);
	LUA_ADD_FUNCTION(L, square); 
	LUA_ADD_FUNCTION(L, rect); 
	LUA_ADD_FUNCTION(L, quad);
	LUA_ADD_FUNCTION(L, line);
	LUA_ADD_FUNCTION(L, triangle);
	LUA_ADD_FUNCTION(L, point);
	LUA_ADD_FUNCTION(L, arc);

	// Shapes 3D
	LUA_ADD_FUNCTION(L, box);
	LUA_ADD_FUNCTION(L, torus);
	LUA_ADD_FUNCTION(L, cylinder);
	LUA_ADD_FUNCTION(L, sphere);
	LUA_ADD_FUNCTION(L, plane);

	// Geometry
	LUA_ADD_FUNCTION(L, loadModel);
	LUA_ADD_FUNCTION(L, model);
	LUA_ADD_FUNCTION(L, debugMode);

	// Transform
	LUA_ADD_FUNCTION(L, translate);
	LUA_ADD_FUNCTION(L, scale);
	LUA_ADD_FUNCTION(L, rotate);

	LUA_ADD_FUNCTION(L, rotateX);
	LUA_ADD_FUNCTION(L, rotateY);
	LUA_ADD_FUNCTION(L, rotateZ);

	// Camera
	LUA_ADD_FUNCTION(L, orbitControl);

	// Typography
	LUA_ADD_FUNCTION(L, loadFont);
	LUA_ADD_FUNCTION(L, text);
	LUA_ADD_FUNCTION(L, textSize);
	LUA_ADD_FUNCTION(L, textAlign);
	LUA_ADD_FUNCTION(L, textFont);

	// Images
	lu5_image_bind(L);
	LUA_ADD_FUNCTION(L, image);
	LUA_ADD_FUNCTION(L, loadImage);

	// OOP
	LUA_ADD_FUNCTION_BY_NAME(L, "class", lu5_class);

	// Vector
	lu5_bind_vector(L);

	// MATH
	LUA_ADD_FUNCTION_BY_NAME(L,"randomSeed", lu5_randomSeed);
	LUA_ADD_FUNCTION_BY_NAME(L,	   "random", lu5_random);
	LUA_ADD_FUNCTION_BY_NAME(L,	    "round", lu5_round);
	LUA_ADD_FUNCTION_BY_NAME(L,	     "ceil", lu5_ceil);
	LUA_ADD_FUNCTION_BY_NAME(L,	    "floor", lu5_floor);
	LUA_ADD_FUNCTION_BY_NAME(L,	      "sin", lu5_sin);
	LUA_ADD_FUNCTION_BY_NAME(L,	      "cos", lu5_cos);
	LUA_ADD_FUNCTION_BY_NAME(L,	      "tan", lu5_tan);
	LUA_ADD_FUNCTION_BY_NAME(L,	      "max", lu5_max);
	LUA_ADD_FUNCTION_BY_NAME(L,	      "min", lu5_min);
	LUA_ADD_FUNCTION_BY_NAME(L,	      "abs", lu5_abs);
	LUA_ADD_FUNCTION_BY_NAME(L,	      "map", lu5_map);
	LUA_ADD_FUNCTION_BY_NAME(L,	     "dist", lu5_dist);
	LUA_ADD_FUNCTION_BY_NAME(L, "constrain", lu5_constrain);

	lu5_register_constants(L);
}
